---
- name: Starting all deploy tasks
  hosts: all
  become: yes
  gather_facts: no
  
  tasks:
    - name: Ensure wget is installed
      package:
        name: wget
        state: present
      register: wget_install
      ignore_errors: yes
    
    - name: Create worker directory if it doesn't exist
      file:
        path: /tmp/worker
        state: directory
        mode: '0755'

    - name: Download worker using wget
      command: |
        wget --recursive --no-parent --no-host-directories --cut-dirs=2 --reject "index.html*" -P /tmp/worker \
        http://{{ proj_ip }}:{{ file_port }}/src/worker/
      register: wget_result

    - name: Compile worker
      command: g++ -o worker.o worker.cpp get-specs.cpp new-tasks.cpp -lcrypt -lpthread
      args:
        chdir: /tmp/worker
      register: compile_result 
      ignore_errors: yes

    - name: Run worker
      command: /tmp/worker/worker.o {{ hashed }} {{ proj_ip }} {{ proj_port }} {{ chunk_size}}
      register: run_result

    - name: Display download status
      debug:
        msg: "Download completed successfully on {{ inventory_hostname }}"
      when: wget_result is success

    - name: Handle download failures
      debug:
        msg: "Failed to download on {{ inventory_hostname }}. Error: {{ wget_result.stderr }}"
      when: wget_result is failed