---
- name: Starting all deploy tasks
  hosts: all
  become: yes
  gather_facts: no
  
  tasks:
    - name: Ensure wget is installed
      package:
        name: wget
        state: present
      register: wget_install
      ignore_errors: yes

    - name: Check if worker already exists
      stat:
        path: /tmp/worker.cpp
      register: client_file

    - name: Download worker using wget
      command: wget http://192.168.64.211:8000/src/worker.cpp -O /tmp/worker.cpp
      register: wget_result
      failed_when: wget_result.rc != 0
      retries: 3
      delay: 5
      until: wget_result is not failed

    - name: Compile worker
      command: g++ -o /tmp/worker.o /tmp/worker.cpp
      register: compile_result
      ignore_errors: yes

    - name: Run worker
      command: /tmp/worker.o
      register: run_result
      when: compile_result.rc == 0
      async: 1

    - name: Display download status
      debug:
        msg: "Download completed successfully on {{ inventory_hostname }}"
      when: wget_result is success

    - name: Handle download failures
      debug:
        msg: "Failed to download on {{ inventory_hostname }}. Error: {{ wget_result.stderr }}"
      when: wget_result is failed